---
title: "SEAsnake vignette"
subtitle: "snakemake pipeline from fastq to counts"
author: "Kim Dill-McFarland, kadm@uw.edu"
date: "version `r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: no
  pdf_document:
    toc: yes
    toc_depth: '3'
editor_options:
  chunk_output_type: console
urlcolor: blue
---

# Introduction


See our [tutorial](https://github.com/BIGslu/tutorials/blob/main/RNAseq/1.Hawn_RNAseq_fastq.to.counts.pdf) for further details.

# Pipeline

1. Quality assess sequences with [FastQC](https://www.bioinformatics.babraham.ac.uk/projects/fastqc/)
2. Remove adapters and filter low quality sequences with [AdapterRemoval](https://adapterremoval.readthedocs.io/en/latest/)
3. Align to reference genome with [STAR](https://github.com/alexdobin/STAR)
4. Quality filter alignments with [samtools](http://www.htslib.org/) `view`
5. Quality assess alignments with [samtools](http://www.htslib.org/) `flagstat` and/or [Picard](https://broadinstitute.github.io/picard/) `CollectRnaSeqMetrics`
6. Count reads in genes with [Subread](http://subread.sourceforge.net/) `featureCounts`

# Software
## Resource requirements

**RAM**: Indexing the human genome requires a minimum of 40 GB of RAM. If your reference genome is smaller or you already have a built index, you may be able to use less RAM. If you have many samples, you may need to use more RAM. The most common pipeline failure is running out of RAM so when in doubt, choose the larger option.

**CPU**: We recommend at least 1 CPU per sample to a minimum of 8 CPUs for this pipeline. More CPU usage will increase RAM usage, so if you have limited RAM, scale down the number of CPUs used.

**Storage**: SEAsnake itself is a small program (< 100 MB) with the vignette data adding an additional 32 GB. Thus, storage needs depend almost entirely on your sample size and sequencing depth of those samples. We recommend 65 GB of storage per 10 fastq files to be run. This comes to roughly 1 TB for 150 fastq or 75 paired-end samples.

## AWS AMI

## Other resources

# SEAsnake

# Results

# Contribute to SEAsnake

# Cite SEAsnake

