SampleList:
   test_S1:
    sample: 'test_S1'
    R1: 'data/test_S1_L005_R1_001'
    R2: 'data/test_S1_L005_R2_001'
   test_S2:
    sample: 'test_S2'
    R1: 'data/test_S2_L005_R1_001'
    R2: 'data/test_S2_L005_R2_001'

trim5p: 10
trimAdapt: True
adapter1: AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
adapter2: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT
release: 104
threads: 6
