sample_list:
   test2_S1: 
    sample:  test2_S1
    R1:  data/test2_S1_L005_R1_001.fastq.gz
    R2:  data/test2_S1_L005_R2_001.fastq.gz
   test2_S2: 
    sample:  test2_S2
    R1:  data/test2_S2_L005_R1_001.fastq.gz
    R2:  data/test2_S2_L005_R2_001.fastq.gz
	
trim5p:
    10
trimAdapt:
    yes
adapter1:
    AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
adapter2:
    AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT
release:
    104
threads:
    6
